// Generated by CoffeeScript 2.6.1
var calc, calc_main, init, init_st, lot, reflect_games, reflect_main_game, set_game, start, stop;

window.moneys = {};

window.money_histories = {};

window.status = {};

window.games = {};

window.step = 0;

window.titles = ['所持金3n', '所持金3n+1', '所持金3n+2'];

window.main_game = {
  p: {
    game_a: 0.5,
    game_b: 0.5
  }
};

window.DEFAULT_GAMES = {
  'game_a': {
    title: 'ゲームA',
    p: [[0, 0.48, 0.52], [0.52, 0, 0.48], [0.48, 0.52, 0]],
    to: [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
    gain: [[0, 1, -1], [-1, 0, 1], [1, -1, 0]]
  },
  'game_b': {
    title: 'ゲームB',
    p: [[0, 0.01, 0.99], [0.15, 0, 0.85], [0.85, 0.15, 0]],
    to: [[0, 1, 2], [0, 1, 2], [0, 1, 2]],
    gain: [[0, 1, -1], [-1, 0, 1], [1, -1, 0]]
  }
};

window.timer = null;

$().ready(function() {
  init();
  return $('#start').on('click', function() {
    if (window.timer === null) {
      return stop();
    } else {
      return start();
    }
  });
});

start = function() {
  stop();
  init();
  return startInterval;
};

stop = function() {
  if (window.timer === null) {
    clearInterval(window.timer);
  }
  return window.timer = null;
};

calc = function() {};

calc_main = function() {
  var lot, p_total;
  lot = Math.random();
  p_total = 0;
  return Object.keys(window.main_game.p).map(function(game_name) {
    var p;
    p = window.main_game.p[game_name];
    return p_total += p;
  });
};

init = function() {
  window.games = window.DEFAULT_GAMES;
  init_st();
  reflect_games();
  return reflect_main_game();
};

init_st = function() {
  window.moneys = {
    game_main: 0
  };
  window.status = {
    game_main: 0
  };
  window.money_histories = {
    game_main: 0
  };
  window.step = 0;
  return Object.keys(window.main_game.p).map(function(game_name) {
    window.moneys[game_name] = 0;
    window.status[game_name] = 0;
    return window.money_histories[game_name] = [0];
  });
};

reflect_main_game = function() {
  var tbody, thead;
  thead = $('#game_main thead');
  thead.html('').append($('<tr>').append($('<th>').html('ゲーム')).append($('<th>').html('確率')));
  tbody = $('#game_main tbody');
  tbody.html('');
  return Object.keys(window.main_game.p).map(function(game_name) {
    var p, tr;
    p = window.main_game.p[game_name];
    tr = $('<tr>');
    tr.append($('<td>').html(window.games[game_name].title)).append($('<td>').html('' + (p * 100) + '%'));
    return tbody.append(tr);
  });
};

reflect_games = function() {
  return Object.keys(window.games).map(function(k) {
    var tbody, thead, tr;
    thead = $('#' + k + ' thead');
    thead.html('');
    tr = $('<tr>').append($('<th>').html('状態＼遷移先'));
    window.titles.map(function(title) {
      return tr.append($('<th>').html(title));
    });
    thead.append(tr);
    tbody = $('#' + k + ' tbody');
    tbody.html('');
    return window.games[k].p.map(function(v, index) {
      tr = $('<tr>').append($('<th>').html(window.titles[index]));
      v.map(function(p, to_index) {
        var gain, text;
        gain = window.games[k].gain[index][to_index];
        text = (p * 100) + "%<br>" + (gain < 0 ? '<span class="red">-$' : '<span class="blue">$') + Math.abs(gain) + '</span>';
        return tr.append($('<td>').html(p === 0 ? '-' : text));
      });
      return tbody.append(tr);
    });
  });
};

// p[a][b]: aでの発生する確率
// to[a][b]: p発生時の遷移先
// gain[a][b] p発生時の報酬
set_game = function(id, to_array, gain_array) {
  return window.games[id] = {
    p: to_array,
    to: to_array,
    gain: gain_array
  };
};

lot = function() {
  return Math.random();
};
